const express = require("express");
const cors = require("cors");
const axios = require("axios");
require("dotenv").config();

const app = express();
const PORT = 5000;

app.use(cors());

app.get("/api/news", async (req, res) => {
  try {
    const response = await axios.get(
      `https://newsapi.org/v2/top-headlines?country=us&pageSize=5&apiKey=${process.env.NEWS_API_KEY}`
    );

    const botNews = response.data.articles.map((article) => ({
      title: `🤖 BOT SAYS: ${article.title}`,
      description: `${article.description || "No description"} (Generated by bot)`,
      url: article.url,
      image: article.urlToImage,
    }));

    res.json(botNews);
  } catch (error) {
    console.error("News API error:", error.message);
    res.status(500).json({ error: "Failed to fetch news." });
  }
});

app.listen(PORT, () => {
  console.log(`✅ News API server running at http://localhost:${PORT}`);
});
